default: &default
  adapter: postgresql
  enconding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres 
  password: 123456
  host: localhost

development:
  <<: *default
  database: form_nested_development

test:
  <<: *default
  database: form_nested_test

production:
  primary: &primary_production
    <<: *default
    database: form_nested_production
    username: form_nested 
    password: <%= ENV["FORM_NESTED_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: form_nested_production_cache
    migrations_paths: db/cache_migrate 
  queue:
    <<: *primary_production
    database: form_nested_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: form_nested_production_cable
    migrations_paths: db/cable_migrate
